const {chromium}=require('C:/Users/FAC/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const base='http://127.0.0.1:8767/';
(async()=>{
const b=await chromium.launch();const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(base);await p.waitForFunction(()=>window.htmx);await p.evaluate(()=>window.testMarker='same-document');
assert.equal(await p.locator('article').count(),1);assert.equal(await p.locator('.priority').count(),3);
await p.locator('.priority.capacity').click();await p.waitForFunction(()=>document.querySelector('#workspace').dataset.topic==='capacity');assert.equal(await p.locator('.topic').count(),5);
await p.locator('.topic[href="modernization.html#reading"]').click();await p.waitForFunction(()=>document.querySelector('#workspace').dataset.topic==='modernization');
await p.locator('.depth-link').filter({hasText:'Technical detail'}).click();await p.waitForFunction(()=>document.querySelector('#workspace').dataset.depth==='deep');assert.equal(await p.evaluate(()=>window.testMarker),'same-document');assert.match(p.url(),/modernization-deep.html/);assert.match(await p.locator('.prose').innerText(),/Overall protocol: failed/);
await p.screenshot({path:'C:/Users/FAC/Documents/_AI_builds_GPT/Presentations/nsf-v2-deep.png',fullPage:true});
await p.route('**/modernization-mid.html',r=>r.abort());await p.locator('.depth-link').filter({hasText:'More context'}).click();await p.waitForFunction(()=>document.querySelector('#load-status').textContent.includes('could not load'));assert.equal(await p.locator('#workspace').getAttribute('data-depth'),'deep');await p.unroute('**/modernization-mid.html');
await p.route('**/modernization-mid.html',async r=>{await new Promise(resolve=>setTimeout(resolve,700));await r.continue().catch(()=>{})});await p.locator('.depth-link').filter({hasText:'More context'}).click();await p.locator('.depth-link').filter({hasText:'Quick read'}).click();await p.waitForFunction(()=>document.querySelector('#workspace').dataset.depth==='surface');await p.waitForLoadState('networkidle');assert.equal(await p.locator('#workspace').getAttribute('data-depth'),'surface');await p.unroute('**/modernization-mid.html');
await p.goBack();await p.waitForFunction(()=>document.querySelector('#workspace').dataset.depth==='deep');assert.match(p.url(),/modernization-deep.html/);
await p.locator('.priority.learning').click();await p.waitForFunction(()=>document.querySelector('#workspace').dataset.topic==='learning');assert.equal(await p.locator('#workspace').getAttribute('data-depth'),'deep');
await p.locator('.topic[href="outcomes-deep.html#reading"]').click();await p.waitForFunction(()=>document.querySelector('#workspace').dataset.topic==='outcomes');assert.match(await p.locator('.prose').innerText(),/not an SBIR award evaluation/);
await p.locator('#present-toggle').click();assert.equal(await p.locator('.priorities').isVisible(),false);await p.keyboard.press('ArrowRight');await p.waitForFunction(()=>document.querySelector('#workspace').dataset.topic!=='outcomes');await p.keyboard.press('Escape');assert.equal(await p.locator('.priorities').isVisible(),true);
await p.goto(base+'access.html');await p.screenshot({path:'C:/Users/FAC/Documents/_AI_builds_GPT/Presentations/nsf-v2-desktop.png'});
// All complete views remain readable at a narrow viewport, including technical tables.
const mobile=await b.newPage({viewport:{width:375,height:812}});const manifest=JSON.parse(fs.readFileSync('dist/assets/topics.json'));
for(const file of manifest.pages){await mobile.goto(base+file);assert.equal(await mobile.locator('article').count(),1);assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile overflow: '+file)}
await mobile.goto(base+'pathway.html');await mobile.screenshot({path:'C:/Users/FAC/Documents/_AI_builds_GPT/Presentations/nsf-v2-mobile.png',fullPage:true});
await p.goto(base+'modernization-deep.html');await p.evaluate(()=>document.documentElement.style.fontSize='200%');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'200% text overflow');
const nojs=await b.newPage({javaScriptEnabled:false});await nojs.goto(base);await nojs.locator('.priority.access').click();await nojs.locator('.topic').first().click();await nojs.locator('.depth-link').filter({hasText:'Technical detail'}).click();assert.equal(await nojs.locator('#workspace').getAttribute('data-topic'),'pathway');assert.equal(await nojs.locator('#workspace').getAttribute('data-depth'),'deep');
await p.goto(base+'handout.html');await p.emulateMedia({media:'print'});assert.equal(await p.locator('.print-topic:visible').count(),16);await p.pdf({path:'C:/Users/FAC/Documents/_AI_builds_GPT/Presentations/NSF-Convening-Handout.pdf',format:'A4',printBackground:true});
assert.deepEqual(errors,[]);const result={passed:true,standaloneViews:57,printTopics:16,checks:['one main article at a time','three priorities and circular topic menus','HTMX navigation retains document','depth persists between topics','failed request preserves current view','rapid requests cannot apply a stale view','browser back restores topic and depth','speaking path and Escape','all 57 pages fit 375px mobile','200% text no overflow','topic and depth navigation without JavaScript','full printable handout'],pageErrors:errors};fs.writeFileSync('QA.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
