"""Agenda framing: participant proposals, not statements of NSF policy."""
GROUPS = {
'access': ('Access', 'Help more people enter and connect.', ['pathway','portal','fac']),
'capacity': ('Capacity', 'Give useful work the support to advance.', ['opensource','modernization','verification','storage','assistance']),
'learning': ('Learning', 'Make evidence useful to the next decision.', ['gkos','library','outcomes','notebook','observatory']),
}
# label, agenda question, next step, people, progress, guide page, track, stage
TOPICS = {
'pathway': ('Independent researchers', 'Who has useful work but cannot reach the people, infrastructure, or support needed to advance it?', 'Pilot a supported referral path for independent researchers and small teams. Record where the handoff breaks down.', 'Program navigators, independent researchers, research institutions, and regional partners.', 'Time to a useful connection; completed handoffs; reasons people are turned away.', 14, 'C · Innovation infrastructure', 'Discovery → Translation'),
'portal': ('Finding support', 'How can we reduce the time spent finding the right program or partner?', 'Connect existing directories to a named navigator who can make a warm referral and confirm the outcome.', 'Program staff, technical assistance providers, and people seeking support.', 'Referrals that reach a suitable partner, rather than portal visits alone.', 12, 'B · Ecosystem best practices', 'Across the research journey'),
'fac': ('Community partnerships', 'How can research institutions build useful, lasting relationships with communities?', 'Use Florida Armored Combat as a possible partner for shaping a research question together, before choosing a method or making an outcome claim.', 'Community members, researchers, and an accountable institutional partner.', 'A jointly defined question, clear roles, an agreed method, and a useful return to the community.', 14, 'B · Ecosystem best practices', 'Discovery → Validation'),
'opensource': ('Open-source stewardship', 'What support keeps a research tool usable after its first release?', 'Treat maintenance, documentation, testing, and user support as explicit work in a bounded pilot.', 'Maintainers, research software engineers, users, and funding partners.', 'External reuse, maintenance continuity, and reproducible results.', 2, 'C · Innovation infrastructure', 'Translation → Adoption'),
'modernization': ('Software qualification', 'What evidence is needed before a promising tool is ready for the next stage?', 'Use a small qualification case with fixed criteria. Keep agreement, numerical accuracy, and performance as separate claims.', 'Domain researchers, numerical specialists, software engineers, and prospective users.', 'A reviewer can identify the tested scope, failed criteria, and evidence needed for the next decision.', 5, 'A · Barriers to translation', 'Translation → Validation'),
'verification': ('AI and verification', 'Where can AI reduce friction, and where must human judgment remain?', 'Pair AI-assisted work with deterministic checks, explicit evidence requirements, and an accountable human reviewer.', 'Researchers, AI tool builders, domain reviewers, and program evaluators.', 'Review time and correction rates, together with the quality of the final evidence.', 13, 'A · Barriers to translation', 'Across the research journey'),
'storage': ('Evidence stewardship', 'What infrastructure makes a result accessible and understandable later?', 'Connect reports to retained artifacts, integrity checks, clear access terms, and a named custodian.', 'Researchers, repositories, storage providers, and data stewards.', 'An authorized reviewer can find, verify, and interpret the retained record.', 14, 'C · Innovation infrastructure', 'Validation → Reuse'),
'assistance': ('Technical assistance', 'What expertise is missing between a research result and a usable tool?', 'Pilot a small engineering and validation service with clear intake, scope, ownership, and handoff.', 'Research software engineers, domain specialists, maintainers, and regional partners.', 'Useful handoffs, reproducible work, external adoption, and a maintenance plan.', 2, 'C · Innovation infrastructure', 'Translation → Validation → Adoption'),
'gkos': ('Evidence and decisions', 'How can a partnership show why it made a decision, and revise it when evidence changes?', 'Test one evidence record that connects a claim, its sources, review, limits, and next decision.', 'Researchers, evidence reviewers, tool builders, and the people using the result.', 'A new reviewer can trace the claim to evidence and explain what changed after review.', 13, 'B · Ecosystem best practices', 'Across the research journey'),
'library': ('Connected research records', 'How can existing resources connect and scale without losing their custodians or context?', 'Start with a small shared catalog that points to original records and preserves permissions, attribution, corrections, and disagreements.', 'Repository custodians, librarians, researchers, and standards partners.', 'Time to find relevant evidence; usable cross-references; fewer missing source records.', 14, 'C · Innovation infrastructure', 'Discovery → Reuse'),
'outcomes': ('Learning and continued support', 'When does continued support build capability, and when does it become dependency?', 'Record what another attempt changed: uncertainty resolved, capability gained, transition achieved, or a justified stop. Review this alongside commercial or mission progress.', 'Program evaluators, researchers, entrepreneurs, customers, and funding partners.', 'Evidence of learning and transition, with reasons for continuation, redirection, or stopping.', 15, 'D · Funding and investment', 'Validation → Commercialization → Impact'),
'notebook': ('Exploratory research', 'How can early exploratory work be understandable without overstating readiness?', 'Use a bounded notebook to separate the question, assumptions, mathematical or code results, and unresolved tests.', 'Researchers, technical reviewers, and possible collaborators.', 'A reviewer can distinguish an exploratory result from a validated application.', 3, 'A · Barriers to translation', 'Discovery → Translation'),
'observatory': ('Evidence exhibit', 'Can an unfamiliar participant understand what was tested and what remains unresolved?', 'Test a reviewed, sanitized research record as a small exhibit before claiming a ready participant workflow.', 'Exhibit builders, research custodians, reviewers, and intended visitors.', 'Visitors can explain the test, result, evidence, and remaining uncertainty.', 15, 'B · Ecosystem best practices', 'Validation → Communication'),
}
GROUP_INTRO = {
'access': ('Make the next connection easier.', 'A useful idea can stall before it reaches a suitable program, institution, or partner. These proposals focus on the handoff: who can help, who takes responsibility, and whether the connection actually happens.', 'Supported referrals', 'Identify a receiving partner and a navigator. Begin with a small set of independent researchers or community-led questions.', 'Measure completed handoffs and time to useful support.'),
'capacity': ('Support the work between an idea and adoption.', 'Funding is only part of the translation problem. People also need engineering, validation, maintenance, and evidence infrastructure. These examples make that work visible.', 'Engineering and validation support', 'Choose one bounded software or research task, an accountable technical partner, and explicit acceptance criteria.', 'Measure reproducibility, useful adoption, and continuity after the pilot.'),
'learning': ('Make every next decision better informed.', 'Success is more than a count of awards or activities. A useful record explains what happened, what the evidence supports, and why the next step should continue, change, or stop.', 'Reusable research records', 'Connect one reviewed result to its sources, limitations, review, and next decision. Test whether someone outside the project can understand it.', 'Measure review effort, missing evidence, and useful reuse.'),
}
