# GKOS-XW-002 v0.2-draft NIST AI RMF 1.0 row adjudication — PROPOSED, owner/reviewer disposition required.
# class codes: DEC=Direct evidence candidate, CON=Contributes, DD=Deployment-declared, NDM=No direct mapping, SUP=Superseded
ROWS = [
('GKOS-CONFORMANCE-001', 'DEC', ['MEASURE 1.1'], 'conformance result (UNEVALUATED outcome)', 'Documents what was not measured; MEASURE 1.1 asks for exactly this disclosure.'),
('GKOS-CONFORMANCE-002', 'CON', ['MEASURE 1.1'], 'conformance-manifest; non-zero exit', 'Blocks over-claiming; sufficiency of the claim boundary is organizational.'),
('GKOS-CONFORMANCE-003', 'NDM', [], '—', 'Fixture/adapter boundary rule does not require independent AI-system assessment; no direct RMF outcome nexus.'),
('GKOS-IDENTITY-001', 'NDM', [], '—', 'Identifier format rule; no RMF outcome nexus.'),
('GKOS-IDENTITY-002', 'NDM', [], '—', 'Legacy identifier validity; no RMF outcome nexus.'),
('GKOS-IDENTITY-003', 'CON', ['MEASURE 2.8'], 'migration record preserving uid', 'Preserves traceability across migration.'),
('GKOS-IDENTITY-004', 'NDM', [], '—', 'Anti-inference rule for identifier ordering; important GKOS authority semantics, but no direct AI RMF outcome nexus.'),
('GKOS-LINEAGE-001', 'CON', ['MEASURE 2.8'], 'lineage graph with explicit branches', 'Branch preservation supports inspectability.'),
('GKOS-LINEAGE-002', 'NDM', [], '—', 'Derivation rule for invalid_at; technical only.'),
('GKOS-LINEAGE-003', 'CON', ['MEASURE 2.8'], '—', 'No silent authoritative selection; accountability for succession remains human.'),
('GKOS-RECEIPT-001', 'DEC', ['MEASURE 2.8'], 'State-Change Receipt', 'Universal receipting is the core accountability record. MANAGE 4.3 NOT assigned to routine receipts.'),
('GKOS-RECEIPT-002', 'DEC', ['MEASURE 2.8', 'GOVERN 2.1'], 'State-Change Receipt (actor class, predicate id/version)', 'Actor class in record evidences documented roles.'),
('GKOS-RECEIPT-003', 'CON', ['MEASURE 2.5', 'MEASURE 2.8'], 'rollback/compensation record; manifest binding-mechanism declaration', 'Receipt-binding failure handling supports reliable, accountable operation. Not MANAGE 2.4 or 4.1 by itself: transaction rollback is neither AI-system deactivation nor a post-deployment monitoring plan.'),
('GKOS-POLICY-001', 'DD', ['GOVERN 1.2', 'MEASURE 2.8'], 'policy/predicate identity and version', 'GKOS mandates explicit identity/version and blocks silent substitution; the organization supplies policy substance and determines whether trustworthiness is integrated.'),
('GKOS-RETENTION-001', 'DD', ['GOVERN 1.1'], 'hold-predicate consultation record', 'Legal/regulatory obligation is deployment-declared.'),
('GKOS-RETENTION-002', 'DEC', ['MEASURE 2.8'], 'disposition receipt binding predicate id/version/result', 'Documents the basis of a disposition.'),
('GKOS-RETENTION-003', 'DD', ['GOVERN 1.1', 'MANAGE 1.3'], 'fail-closed record; human-disposition routing', 'Avoidance response to indeterminate legal predicate; GKOS does not decide the obligation.'),
('GKOS-REENTRY-001', 'CON', ['MEASURE 2.8'], 'new Layer-1 Source Record', 'Provenance preserved as property of the artifact.'),
('GKOS-REENTRY-002', 'CON', ['MEASURE 2.8'], 're-entered source with fresh standing', 'No inherited authority or standing.'),
('GKOS-REENTRY-003', 'CON', ['MEASURE 2.8'], 'predecessor unchanged', 'Non-destructive re-entry.'),
('GKOS-REENTRY-004', 'DEC', ['GOVERN 3.2', 'MEASURE 2.8'], 'human/delegated supersession declaration', 'Explicit human or bounded-delegation supersession supports differentiated human-AI authority and accountability. Semantic knowledge supersession is not MANAGE 2.4 AI-system deactivation.'),
('GKOS-DELEGATION-001', 'DEC', ['GOVERN 2.1', 'GOVERN 3.2'], 'delegation grant (bounded, versioned, expiring)', 'Documented, differentiated human-AI authority.'),
('GKOS-DELEGATION-002', 'DEC', ['GOVERN 3.2', 'MANAGE 1.3'], 'routine/major classification by versioned predicate', 'Major/indeterminate → prior human disposition is a planned risk response.'),
('GKOS-DELEGATION-003', 'NDM', [], '—', 'Raise-only nondeterministic checking is a GKOS control-integrity rule; no direct AI RMF outcome nexus.'),
('GKOS-DELEGATION-004', 'SUP', [], '—', 'Superseded for v0.81 line; see GKOS-REVIEW-001..003.'),
('GKOS-DELEGATION-005', 'DEC', ['GOVERN 3.2', 'GOVERN 2.1'], 'delegation scope', 'Capability ≠ authority; no general write authority implied.'),
('GKOS-DELEGATION-006', 'CON', ['GOVERN 3.2', 'MANAGE 4.1'], 'delegation freeze on overdue review; exception receipt', 'Overdue-review freeze and bounded exception contribute to human-AI oversight and monitoring/override. Not MANAGE 2.4 absent AI-system performance/outcome inconsistency.'),
('GKOS-PROFILE-001', 'CON', ['MEASURE 1.1'], 'conformance-manifest (Core)', 'Claim scope documented.'),
('GKOS-PROFILE-002', 'CON', ['MEASURE 1.1'], 'conformance-manifest (Advanced)', 'Claim scope documented.'),
('GKOS-PROFILE-003', 'CON', ['MAP 1.1'], 'conformance-manifest constraints (read-only)', 'Intended use bounded: no consequential action under the claim.'),
('GKOS-PROFILE-004', 'DEC', ['MEASURE 2.8'], 'conformance-manifest (release, GKX, commit, fixtures, exceptions, assessment type)', 'Complete claim binding. GOVERN 4.2 NOT assigned: manifest documents conformance status, not risk/impact.'),
('GKOS-PROFILE-005', 'CON', ['MEASURE 2.5'], 'gate-code violation fixtures', 'Executable negative evidence for fail-closed behavior supports reliability demonstration.'),
('GKOS-PROFILE-006', 'CON', ['MEASURE 1.1'], 'conformance-manifest exceptions', 'No silent exclusion while retaining claim.'),
('GKOS-PROFILE-007', 'DEC', ['MEASURE 2.8', 'MEASURE 2.9'], 'Viewer/Projection output', 'Exposes provenance, epistemic state, contradictions, limitations to the reader.'),
('GKOS-CANON-001', 'CON', ['MEASURE 2.8'], 'GKX-CBOR-1 canonical artifacts', 'Determinism basis for inspectable artifacts. Not MEASURE 2.7.'),
('GKOS-CANON-002', 'CON', ['MEASURE 2.8'], 'duplicate-key refusal', 'Prevents silent loss in the record.'),
('GKOS-CANON-003', 'NDM', [], '—', 'Numeric representation rule; no RMF outcome nexus.'),
('GKOS-CANON-004', 'NDM', [], '—', 'Timestamp syntax and anti-ordering rule are technical canonicalization semantics; no direct AI RMF outcome nexus.'),
('GKOS-CANON-005', 'NDM', [], '—', 'Text normalization rule; no RMF outcome nexus.'),
('GKOS-CANON-006', 'NDM', [], '—', 'Absent/null/empty distinction; representation only.'),
('GKOS-CANON-007', 'CON', ['MEASURE 2.7', 'MEASURE 2.8'], 'SHA-256 canonical hash binding policy/compiler/selection refs', 'Only CANON row retaining 2.7: integrity binding is security/resilience evidence.'),
('GKOS-CANON-008', 'CON', ['MEASURE 2.8'], 'declared human rendering + parser/verifier', 'Human-readable round trip supports inspectability/accountability of GKOS artifacts; it does not by itself explain or validate an AI model under MEASURE 2.9.'),
('GKOS-CONTEXT-001', 'DEC', ['MAP 1.1', 'MEASURE 2.8'], 'selection envelope', 'Purpose, recipient, actors, omissions captured. MAP 1.6 removed (stakeholder requirements elicitation is not this).'),
('GKOS-CONTEXT-002', 'CON', ['MEASURE 2.5', 'MEASURE 2.8'], 'context-manifest assembly log', 'Reproducible assembly; no live calls.'),
('GKOS-CONTEXT-003', 'CON', ['MEASURE 2.5'], 'identical manifest bytes/hash', 'Replay determinism.'),
('GKOS-CONTEXT-004', 'DEC', ['MEASURE 2.8', 'MEASURE 2.9'], 'context-manifest (contradictions, warnings, restrictions, omissions)', 'Required disclosure in the presented context.'),
('GKOS-CONTEXT-005', 'DEC', ['MEASURE 2.8'], 'Decision Record binding manifest id/version/hash', 'Exact material reviewed is bound to the disposition.'),
('GKOS-AUTHUSE-001', 'DEC', ['MEASURE 2.8'], 'Authorized Use Record', 'Use bound to exact context hash.'),
('GKOS-AUTHUSE-002', 'CON', ['MEASURE 2.5', 'MEASURE 2.7'], 'refusal receipt on hash mismatch', 'Integrity failure fails closed; 2.7 retained because mismatch is tamper/integrity evidence.'),
('GKOS-AUTHUSE-003', 'DEC', ['MEASURE 2.8'], 'authority-basis validity fields', 'Documents valid authority at action time and fail-closed treatment of invalid authority. Authority expiry/revocation alone is not MANAGE 2.4 AI-system deactivation.'),
('GKOS-AUTHUSE-004', 'DEC', ['GOVERN 2.1', 'GOVERN 3.2'], 'actor-role fields; delegation chain', 'Proposing/reviewing/authorizing/executing distinct. GOVERN 1.5 NOT assigned.'),
('GKOS-AUTHUSE-005', 'DEC', ['MEASURE 2.8'], 'Refusal Receipt', 'Gate closure documented with predicate and inputs.'),
('GKOS-AUTHUSE-006', 'DEC', ['MANAGE 4.1', 'MEASURE 2.8'], 'Authorized Use Record outcome + correction/rollback/escalation route', 'Recovery and override route is the 4.1 nexus.'),
('GKOS-AUTHUSE-007', 'CON', ['MEASURE 2.8'], 'GKOS-GATE-L7-001 refusal; captured evaluation time', 'Captured authority interval and refusal evidence contribute to accountability. Authority interval expiry alone is not MANAGE 2.4 AI-system deactivation.'),
('GKOS-EFFECT-001', 'CON', ['MAP 1.1'], 'typed effect-scope vocabulary', 'Scope of intended effect made explicit.'),
('GKOS-EFFECT-002', 'DEC', ['GOVERN 3.2', 'MANAGE 1.3'], 'scope-containment check', 'Effect must sit within human-granted standing and delegation.'),
('GKOS-EFFECT-003', 'CON', ['MANAGE 1.3'], 'fail-closed on indeterminate scope', 'Avoidance response; not system deactivation.'),
('GKOS-REVIEW-001', 'DEC', ['GOVERN 3.2', 'GOVERN 2.1'], 'review-lifecycle entry record', 'Authorized review precedes acceptance.'),
('GKOS-REVIEW-002', 'DEC', ['MEASURE 2.8'], 'append-only Decision Record bound to exact evidence', 'Disposition traceable to evidence reviewed.'),
('GKOS-REVIEW-003', 'DEC', ['GOVERN 2.1', 'GOVERN 3.2'], 'role separation; different-model-family agent reviewer; sealed packet; human escalation', 'No self-approval; differentiated human-AI roles and bounded human escalation. This is proposal review, not necessarily the regular AI-system assessment described by MEASURE 1.3.'),
('GKOS-REVIEW-004', 'DEC', ['MEASURE 2.8'], 'append-only disposition history', 'No silent rewriting. MANAGE 4.3 NOT assigned to routine dispositions.'),
('GKOS-DISCLOSURE-001', 'CON', ['MEASURE 2.10', 'MEASURE 2.7'], 'disclosure authorization; noninterference evidence', 'Privacy and security outcomes; legal basis for protection is deployment-declared.'),
]
